[package]
name = "py2rust"
version = "0.1.0"
authors = ["rollrat <rollrat@inha.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
